# Generated by Django 3.1.8 on 2021-05-03 08:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=200)),
                ('person_name', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=200)),
                ('birth', models.DateField(default=datetime.date.today)),
                ('onset_date', models.DateField(default=datetime.date.today)),
                ('confirm_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=200)),
                ('venue_location', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('x_coordinate', models.DecimalField(decimal_places=3, max_digits=10)),
                ('y_coordinate', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(max_length=200)),
                ('cases', models.ManyToManyField(blank=True, through='covid.Attendance', to='covid.Case')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='events',
            field=models.ManyToManyField(blank=True, through='covid.Attendance', to='covid.Event'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.case'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.event'),
        ),
    ]
