# Generated by Django 3.1.8 on 2021-04-25 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=200)),
                ('person_name', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=200)),
                ('birth', models.DateTimeField()),
                ('onset_date', models.DateTimeField()),
                ('confirm_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=200)),
                ('venue_location', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('x_coordinate', models.DecimalField(decimal_places=3, max_digits=10)),
                ('y_coordinate', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.case')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.event')),
            ],
        ),
    ]
