# Generated by Django 3.1.8 on 2021-04-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='events',
            field=models.ManyToManyField(through='covid.Attendance', to='covid.Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='cases',
            field=models.ManyToManyField(through='covid.Attendance', to='covid.Case'),
        ),
        migrations.AlterField(
            model_name='case',
            name='birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='case',
            name='confirm_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='case',
            name='onset_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
    ]
