# Generated by Django 3.1.8 on 2021-05-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.IntegerField(max_length=200),
        ),
    ]
