# Generated by Django 3.1.8 on 2021-04-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_auto_20210425_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='birth',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='case',
            name='confirm_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='case',
            name='onset_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
