# Generated by Django 3.1.8 on 2021-04-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_auto_20210425_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='events',
            field=models.ManyToManyField(to='covid.Event'),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
